// chara.hpp : character (procedurally-painted sprite sheets)
//
// Pixel art lives in chara_data.hpp as plain hex-digit strings (1 char = 1
// of 8 per-sprite palette slots), exactly as it was authored inline in the
// original chara.lua. See chara_data.hpp's header comment: it is
// auto-generated by tools/gen_chara_data.py, do not hand-edit.
#pragma once
#include "db.hpp"
#include "chara_data.hpp"
#include <cstdlib>

namespace db {

namespace detail {

inline void paint_def(const SpriteDef& def, Userdata& target, int scale) {
    int col[8];
    for (int j = 0; j < 8; j++) {
        char buf[3] = { def.colors[j * 2], def.colors[j * 2 + 1], 0 };
        int slot = (int)std::strtol(buf, nullptr, 16);
        col[j] = app.color_[slot];
    }
    for (int y = 0; y < def.h; y++) {
        const char* row = def.rows[y];
        for (int x = 0; x < def.w; x++) {
            int c = row[x] - '0';
            if (c > 0) {
                int idx = c < 8 ? c : 7;
                int cc = col[idx];
                if (scale == 1) {
                    target.set(def.u + x, def.v + y, cc);
                } else {
                    target.set(def.u + x * 2 + 0, def.v + y * 2 + 0, cc);
                    target.set(def.u + x * 2 + 1, def.v + y * 2 + 0, cc);
                    target.set(def.u + x * 2 + 0, def.v + y * 2 + 1, cc);
                    target.set(def.u + x * 2 + 1, def.v + y * 2 + 1, cc);
                }
            }
        }
    }
}

} // namespace detail

// initialize sprite character
inline void chinitspr() {
    app.gpage2_ = Userdata(256, 512);
    for (int y = 0; y < 512; y++)
        for (int x = 0; x < 256; x++)
            app.gpage2_.set(x, y, 0x3f);

    for (const auto& def : kCharaSprites)
        detail::paint_def(def, app.gpage2_, 1);
}

// initialize bg character
inline void chinitbg() {
    app.gpage3_ = Userdata(256, 512);
    for (int y = 0; y < 512; y++)
        for (int x = 0; x < 512; x++)
            app.gpage3_.set(x, y, 0x3f);

    for (const auto& def : kCharaBg)
        detail::paint_def(def, app.gpage3_, 2);

    // bg to spr: slice gpage3_ into 256 16x16 tiles usable as sprite pages.
    // NOTE: faithfully ported from chara.lua's `n % 32` / `n // 32`, even
    // though gpage3_ is only 256px (16 tiles) wide -- for n % 32 >= 16 this
    // reads past the buffer edge and get() silently returns 0 (opaque
    // black), so roughly half of these 256 tiles come out solid black
    // rather than the transparent (0x3f) default. Unconfirmed whether
    // that's an authentic quirk of the original or a latent bug in it;
    // revisit once course.lua (the actual consumer of these tiles via
    // sppage()) is ported and we can see which indices it expects.
    for (int n = 0; n < 256; n++) {
        int u = (n % 32) * 16;
        int v = (n / 32) * 16;
        Userdata ud(16, 16);
        for (int y = 0; y < 16; y++)
            for (int x = 0; x < 16; x++)
                ud.set(x, y, app.gpage3_.get(u + x, v + y));
        set_spr(n, std::move(ud));
    }
}

// initialize character
inline void chinit() {
    chinitspr();
    chinitbg();
}

} // namespace db
